name: build-package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      platform:
        description: '选择构建平台'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - linux
          - macos
          - cross-platform

env:
  DEB_PKGS: >-
    g++ meson appstream gettext libgoogle-glog-dev libgtk-3-dev libglib2.0-dev
    libjsoncpp-dev libsigc++-2.0-dev libayatana-appindicator3-dev
  MAC_PKGS: >-
    meson appstream gettext glog gtk+3 jsoncpp gtk-mac-integration libsigc++@2
    create-dmg

jobs:
  build-cross-platform:
    if: github.event.inputs.platform == 'all' || github.event.inputs.platform == 'cross-platform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        distro: [ubuntu20.04]
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            apt-get update -q -y
            apt-get install -q -y ${{ env.DEB_PKGS }}
          run: |
            # 使用特定版本的编译选项
            CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_58 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_58" \
            CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_58 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_58" \
            meson setup build \
                --default-library=static \
                -Db_coverage=false \
                -Dwerror=false \
                -Dbuildtype=release \
                -Dwarning_level=0

            # 编译主程序
            meson compile -C build

            # 复制构建产物
            cp build /artifacts/iptux-${{ matrix.arch }}

  build-on-mac:
    if: github.event.inputs.platform == 'all' || github.event.inputs.platform == 'macos'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Homebrew cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-v1
      - name: brew install
        run: brew install --display-times ${{ env.MAC_PKGS }}
      - name: Build
        run: |
          # 使用更多的警告忽略选项
          CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -Wno-sign-compare -Wno-deprecated-declarations -Wno-cast-function-type" \
          CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -Wno-sign-compare -Wno-deprecated-declarations -Wno-cast-function-type" \
          meson setup build \
              --default-library=static \
              -Db_coverage=false \
              -Dwerror=false \
              -Dbuildtype=release \
              -Dwarning_level=0

          # 编译主程序
          meson compile -C build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iptux-macos
          path: build/src/main/iptux
          retention-days: 7
